### PR TITLE
Update node/npm version

### LINKED ISSUE #47: Update versions of Node/NPM used
As per titile. Update the repo and docs to use the latest LTS version of node/npm.

### PR DESCRIPTION
**Pull request by drcoolsanjeev**
upgrade node to 14.15.0 LTS version and update minor versions in package.json 

Signed-off-by: Sanjeev Kumar <sanjekum@redhat.com>

### CODE REVIEW

**Review by JQrdan — APPROVED** [review]
LGTM, thankfully most of our docker images and actions were already upgraded to node 14 through other means

**Review by pmuir — APPROVED** [review]

**Review by dlabaj — APPROVED** [review]

**Comment by nictownsend** [comment]
@drcoolsanjeev can you rebase please ready for a merge

**Review by matthew-chirgwin — CHANGES_REQUESTED** [review]
This LGTM, but as mentioned, needs to be rebased due to conflicts

**Review by scholzj — APPROVED** [review]

**Comment by drcoolsanjeev** [comment]
@matthew-chirgwin Already rebased the branch with master yesterday after nictownsend's comment

**Review by matthew-chirgwin — APPROVED** [review]

**Pull request merged**
