### PR TITLE
feat: add info about logging

### PR DESCRIPTION
**Pull request by ajborley**
Contributes to: #24

Signed-off-by: Andrew Borley <borley@uk.ibm.com>

### CODE REVIEW

**Review by matthew-chirgwin — APPROVED** [review]
LGTM

**Review by scholzj — APPROVED** [review]

**Review by dlabaj — APPROVED** [review]
LGTM for typescript we can get the types here for pino (https://www.npmjs.com/package/@types/pino)

**Comment by matthew-chirgwin** [comment]
@ajborley would you mind raising an issue to implement the logging? Once done, I will merge this

**Comment by ajborley** [comment]
Raised #42 and #43 for implementation.

**Pull request merged**
